Feat/use local storage keep alive
equinor/amplify-components pull request #330
Opened 2023-11-08 11:04 UTC by aslakihle

2023-11-09 13:35 UTC, mariush2 reviewed
Looks good! Just add "ms" changes we talked about in frontend status👏🏻

2023-11-09 18:21 UTC, mariush2 requested changes

2023-11-09 18:21 UTC, mariush2 commented on src/hooks/useLocalStorage.ts
> +  keepAlive?: number
This should be "keepAliveMs" as well

2023-11-10 07:39 UTC, aslakihle commented on src/hooks/useLocalStorage.ts
> +  keepAlive?: number
👀 🙈

2023-11-10 07:43 UTC, mariush2 approved these changes

2023-11-10 07:44 UTC, merged