Fix/update topbar
equinor/amplify-components pull request #439
Opened 2024-02-14 13:21 UTC by AmandaElvkull

2024-02-14 14:11 UTC, aslakihle requested changes

2024-02-14 14:11 UTC, aslakihle commented on src/components/Navigation/TopBar/TopBar.styles.tsx
> +import { UnreadRedDot } from 'src/components/Navigation/TopBar/Notifications/Notifications';
This import could be shortened. 
 './Notifications/Notifications' i think (not 100% sure so did not do suggestion 🙈😂 )

2024-02-15 09:00 UTC, aslakihle commented on src/components/Navigation/TopBar/Notifications/Notifications.test.tsx
Hei

2024-02-15 11:05 UTC, mariush2 commented on src/components/Navigation/TopBar/Notifications/Notifications.tsx
> +  // Box-sizing is a quickfix for use in PWEX because of global styling
Good idea to have a comment here to explain 🥳

2024-02-15 12:01 UTC, mariush2 requested changes
Smaller stuff

2024-02-15 12:56 UTC, mariush2 approved these changes

2024-02-15 13:03 UTC, aslakihle approved these changes

2024-02-15 13:11 UTC, merged